# 1. Imports

In [2]:
import pandas as pd
import numpy as np
import glob
import polars as pl
from pathlib import Path

DATA_PATH = Path("./data/UpdatedData/citibike_2023_combined.parquet/")

# 2. Data Load & Process

In [3]:
df = (
    pl.read_parquet(f"{DATA_PATH}/*.parquet")
    # 1) Parse to datetime and rename in one go
    .with_columns(
        pl.col("started_at").str.to_datetime().alias("start_time"),
        pl.col("ended_at").str.to_datetime().alias("end_time"),
    )
    # 2) Compute ride_time_seconds = end_time - start_time (in seconds)
    .with_columns(
        (pl.col("end_time") - pl.col("start_time"))
        .dt.total_seconds()
        .alias("ride_time_seconds")
    )
    # 3) Order by start_time
    .sort("start_time")
    # 4) Select columns in the exact order you want
    .select(
        "ride_id",
        "rideable_type",
        "start_time",
        "end_time",
        "ride_time_seconds",   # ← right after end_time
        "start_station_name",
        "start_station_id",
        "end_station_name",
        "end_station_id",
        "start_lat",
        "start_lng",
        "end_lat",
        "end_lng",
        "member_casual",
    )
)

df.head()

shape: (5, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ ride_id   ┆ rideable_ ┆ start_tim ┆ end_time  ┆ … ┆ start_lng ┆ end_lat   ┆ end_lng   ┆ member_c │
│ ---       ┆ type      ┆ e         ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ asual    │
│ str       ┆ ---       ┆ ---       ┆ datetime[ ┆   ┆ f64       ┆ f64       ┆ f64       ┆ ---      │
│           ┆ str       ┆ datetime[ ┆ μs]       ┆   ┆           ┆           ┆           ┆ str      │
│           ┆           ┆ μs]       ┆           ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1371D252B ┆ classic_b ┆ 2022-12-1 ┆ 2023-01-0 ┆ … ┆ -73.99253 ┆ null      ┆ null      ┆ casual   │
│ F823F8F   ┆ ike       ┆ 4 11:43:5 ┆ 8 14:08:5 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 4.762     ┆ 3.507     ┆   ┆           ┆           ┆           ┆          │
│ 49762460E ┆ classic_b ┆ 2022-12-2 ┆ 2023-01-0 ┆ … ┆ -73.97077 ┆ 40.696102 ┆ -73.96751 ┆ casual   │
│ 71B1340   ┆ ike       ┆ 8 09:17:2 ┆ 1 09:24:5 ┆   ┆ 6         ┆           ┆           ┆          │
│           ┆           ┆ 8.882     ┆ 7.541     ┆   ┆           ┆           ┆           ┆          │
│ F04D69056 ┆ classic_b ┆ 2022-12-2 ┆ 2023-01-0 ┆ … ┆ -73.97077 ┆ 40.696102 ┆ -73.96751 ┆ casual   │
│ 67F3109   ┆ ike       ┆ 8 09:17:5 ┆ 1 07:39:3 ┆   ┆ 6         ┆           ┆           ┆          │
│           ┆           ┆ 1.549     ┆ 8.879     ┆   ┆           ┆           ┆           ┆          │
│ 0ACCA694D ┆ classic_b ┆ 2022-12-2 ┆ 2023-01-0 ┆ … ┆ -73.92925 ┆ null      ┆ null      ┆ casual   │
│ 85B7BDE   ┆ ike       ┆ 8 11:24:1 ┆ 2 09:47:3 ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ 7.103     ┆ 2.290     ┆   ┆           ┆           ┆           ┆          │
│ 4EDDEF85A ┆ classic_b ┆ 2022-12-2 ┆ 2023-01-0 ┆ … ┆ -74.01322 ┆ 40.751396 ┆ -74.00522 ┆ casual   │
│ 6E6BF1B   ┆ ike       ┆ 8 11:27:3 ┆ 2 19:42:1 ┆   ┆ 1         ┆           ┆ 6         ┆          │
│           ┆           ┆ 9.038     ┆ 1.504     ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### 2.1. Filter Data

1. Remove any data that doesn't have an end station (probably bad data)
2. Remove any data that has a ride time of over 2 hours (probably bad data)

In [ ]:
# remove any start or end_station_name = null
df = df.filter(pl.col("end_station_name").is_not_null())
df= df.filter(pl.col("end_station_id").is_not_null())
df = df.filter(pl.col("start_station_name").is_not_null())
df= df.filter(pl.col("start_station_id").is_not_null())

# filter data out for ride_time < 2 hours or way too short ones like 1 minute
df = df.filter(pl.col("ride_time_seconds") < 2 * 3600)   
df = df.filter(pl.col("ride_time_seconds") >= 60)

df = df.filter(pl.col("start_time").dt.year() == 2023)
df = df.with_columns([
    pl.col("start_time").dt.month().alias("month"),
])

# filter data out for ride time that is negative or zero (not possible)
df = df.filter(pl.col("ride_time_seconds") > 0)

# Remove rides with identical start/end stations (probably some error)
df = df.filter(
    ~(
        (pl.col("start_station_id") == pl.col("end_station_id"))
    )
)

df = df.filter(
    ~(
        (pl.col("start_lat") == pl.col("end_lat"))
        & (pl.col("start_lng") == pl.col("end_lng"))
    )
)

# 3. Check Data

In [11]:
# Rideable type counts
df.select(pl.col("rideable_type").value_counts())

shape: (2, 1)
┌────────────────────────────┐
│ rideable_type              │
│ ---                        │
│ struct[2]                  │
╞════════════════════════════╡
│ {"electric_bike",17416253} │
│ {"classic_bike",17372605}  │
└────────────────────────────┘

In [12]:
# Member type counts
df.select(pl.col("member_casual").value_counts())

shape: (2, 1)
┌─────────────────────┐
│ member_casual       │
│ ---                 │
│ struct[2]           │
╞═════════════════════╡
│ {"casual",6469110}  │
│ {"member",28319748} │
└─────────────────────┘